import type React from 'react';
import {
  BadgeDollarSign,
  BookOpen,
  Bug,
  Building2,
  Calendar,
  ClipboardList,
  Code,
  Database,
  FileText,
  FlaskConical,
  GraduationCap,
  Heart,
  Headphones,
  HeartHandshake,
  PenTool,
  PhoneCall,
  Plus,
  RefreshCw,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Target,
  UserPlus,
  UserSearch,
  Users,
  Wallet,
  Truck,
} from 'lucide-react';

export interface AgentTemplate {
  id: string;
  name: string;
  type: string;
  industry: string;
  description: string;
  features: string[];
  // Model id from the gateway (ex: "openai/gpt-4o"). This can be overridden at deploy-time.
  model: string;
  platform: string;
  budget: number;
  price: string;
  icon: React.ElementType;
  color: string;
  roi?: string;
  complexity?: 'Basic' | 'Advanced' | 'Expert';
}

export const AGENT_TEMPLATE_INDUSTRIES = [
  'all',
  'HR',
  'Enterprise',
  'E-commerce',
  'B2B',
  'Legal',
  'Banking',
  'Technology',
  'Healthcare',
  'Finance',
] as const;

export const AGENT_TEMPLATES: AgentTemplate[] = [
  // ── HR-first templates ────────────────────────────────────────────────────
  {
    id: 'hr-benefits',
    name: 'Benefits Navigator',
    type: 'hr_benefits',
    industry: 'HR',
    description: 'Instantly answers employee questions about health insurance, dental, pension, and benefits enrollment — 24/7, without waiting for an HR email.',
    features: ['Benefits FAQ', 'Enrollment Guidance', 'Policy Explainers', 'Open Enrollment Reminders', 'Claims Support'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1500,
    price: '₹18,000/month',
    icon: Heart,
    color: 'rose',
    roi: 'Reduces benefits-related HR tickets by 60%',
    complexity: 'Basic',
  },
  {
    id: 'hr-onboarding',
    name: 'Onboarding Assistant',
    type: 'hr_onboarding',
    industry: 'HR',
    description: 'Guides new hires through their entire first 30 days — paperwork, introductions, tool access, and manager check-ins — automatically.',
    features: ['Day-1 Checklist', 'Document Collection', 'Tool Access Requests', '30/60/90 Day Plans', 'Manager Nudges'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1200,
    price: '₹15,000/month',
    icon: UserPlus,
    color: 'cyan',
    roi: 'Cuts onboarding admin time by 70%',
    complexity: 'Basic',
  },
  {
    id: 'hr-payroll',
    name: 'Payroll Bot',
    type: 'hr_payroll',
    industry: 'HR',
    description: 'Handles all payslip queries, tax deduction questions, reimbursement status, and payroll discrepancy reports — without pulling HR into every conversation.',
    features: ['Payslip Explainers', 'Tax Form Guidance', 'Reimbursement Status', 'Deduction Breakdown', 'Escalation Routing'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹22,000/month',
    icon: BadgeDollarSign,
    color: 'amber',
    roi: 'Handles 80% of payroll queries without HR intervention',
    complexity: 'Basic',
  },
  {
    id: 'hr-leave',
    name: 'Leave & Attendance Manager',
    type: 'hr_leave',
    industry: 'HR',
    description: 'Processes leave requests, checks balances, flags attendance anomalies, and notifies managers — keeping HR out of the back-and-forth.',
    features: ['Leave Balance Checks', 'Request Processing', 'Attendance Anomaly Alerts', 'Manager Notifications', 'Policy Enforcement'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1000,
    price: '₹12,000/month',
    icon: Calendar,
    color: 'teal',
    roi: 'Saves HR 10+ hours per week on leave admin',
    complexity: 'Basic',
  },
  {
    id: 'hr-policy',
    name: 'Policy Advisor',
    type: 'hr_policy',
    industry: 'HR',
    description: 'Gives employees instant, accurate answers to HR policy questions — code of conduct, expense claims, remote work rules — with full audit trail.',
    features: ['Policy Q&A', 'Expense Guidelines', 'Remote Work Rules', 'Code of Conduct FAQs', 'Audit Trail'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1200,
    price: '₹14,000/month',
    icon: BookOpen,
    color: 'violet',
    roi: 'Reduces policy-related interruptions to HR by 50%',
    complexity: 'Basic',
  },
  // ── Broader domain templates ───────────────────────────────────────────────
  {
    id: '1',
    name: 'Support Agent',
    type: 'customer_support',
    industry: 'E-commerce',
    description: 'AI-powered customer support agent for handling inquiries, order tracking, and common questions.',
    features: ['Order Status Lookup', 'Refund Processing', 'Product Information', 'FAQ Automation', 'Escalation Routing'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹25,000/month',
    icon: Headphones,
    color: 'blue',
  },
  {
    id: '2',
    name: 'Sales Agent',
    type: 'sales',
    industry: 'B2B',
    description: 'Intelligent sales assistant for lead qualification, demo scheduling, and product recommendations.',
    features: ['Lead Qualification', 'Demo Scheduling', 'Product Recommendations', 'CRM Integration', 'Follow-up Automation'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹35,000/month',
    icon: Target,
    color: 'green',
  },
  {
    id: '3',
    name: 'HR Agent',
    type: 'hr',
    industry: 'Enterprise',
    description: 'HR assistant for employee onboarding, policy queries, and leave management.',
    features: ['Employee Onboarding', 'Policy FAQ', 'Leave Management', 'Benefits Information', 'Performance Reviews'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1500,
    price: '₹20,000/month',
    icon: Users,
    color: 'purple',
  },
  {
    id: '4',
    name: 'Legal Agent',
    type: 'legal',
    industry: 'Legal',
    description: 'Legal document assistant for contract review, compliance checking, and risk assessment.',
    features: ['Contract Review', 'Compliance Check', 'Risk Assessment', 'Document Summarization', 'Clause Analysis'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 5000,
    price: '₹50,000/month',
    icon: ShieldCheck,
    color: 'red',
  },
  {
    id: '5',
    name: 'Finance Agent',
    type: 'finance',
    industry: 'Banking',
    description: 'Financial services bot for account queries, loan applications, and transaction support.',
    features: ['Account Queries', 'Loan Applications', 'Transaction Support', 'Fraud Detection', 'Compliance Verification'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 4000,
    price: '₹45,000/month',
    icon: Wallet,
    color: 'amber',
  },
  {
    id: '6',
    name: 'IT Support Agent',
    type: 'it_support',
    industry: 'Technology',
    description: 'IT helpdesk agent for ticket creation, troubleshooting, and knowledge base access.',
    features: ['Ticket Creation', 'Troubleshooting Guide', 'Password Reset', 'System Status', 'Knowledge Base'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹22,000/month',
    icon: Server,
    color: 'cyan',
  },
  {
    id: '7',
    name: 'Healthcare Agent',
    type: 'healthcare',
    industry: 'Healthcare',
    description: 'Patient triage assistant for appointment scheduling, symptom assessment, and provider matching.',
    features: ['Appointment Scheduling', 'Symptom Triage', 'Provider Matching', 'Insurance Verification', 'Follow-up Care'],
    model: 'google/gemini-2.0-flash-001',
    platform: 'Google',
    budget: 4500,
    price: '₹55,000/month',
    icon: FlaskConical,
    color: 'emerald',
  },
  {
    id: '8',
    name: 'Refund Agent',
    type: 'refund',
    industry: 'E-commerce',
    description: 'Specialized refund processing agent with fraud detection and approval workflows.',
    features: ['Fraud Detection', 'Refund Approval', 'Policy Enforcement', 'Manual Review Queue', 'Audit Trail'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹30,000/month',
    icon: RefreshCw,
    color: 'orange',
  },
  {
    id: '9',
    name: 'Onboarding Agent',
    type: 'onboarding',
    industry: 'Enterprise',
    description: 'New employee onboarding agent for paperwork, training, and welcome communications.',
    features: ['Document Collection', 'Training Modules', 'Welcome Sequences', 'Progress Tracking', 'Manager Alerts'],
    model: 'anthropic/claude-3-haiku',
    platform: 'Anthropic',
    budget: 1000,
    price: '₹15,000/month',
    icon: UserPlus,
    color: 'teal',
  },
  {
    id: '10',
    name: 'Compliance Agent',
    type: 'compliance',
    industry: 'Finance',
    description: 'Regulatory compliance monitor for KYC/AML, audit trails, and policy enforcement.',
    features: ['KYC Verification', 'AML Screening', 'Audit Trails', 'Policy Enforcement', 'Risk Alerts'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹65,000/month',
    icon: ShieldAlert,
    color: 'rose',
    roi: 'Reduces compliance risk by 95%',
    complexity: 'Advanced',
  },
  {
    id: '11',
    name: 'Marketing & Content Agent',
    type: 'marketing',
    industry: 'E-commerce',
    description: 'Creative assistant for SEO optimization, social media drafting, and blog post generation.',
    features: ['SEO Optimization', 'Social Media Drafting', 'Blog Post Generation', 'Copy Reviewing', 'Keyword Research'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹35,000/month',
    icon: PenTool,
    color: 'pink',
    roi: 'Boosts content pipeline output by 3x',
    complexity: 'Basic',
  },
  {
    id: '12',
    name: 'Data Analyst Agent',
    type: 'data_analysis',
    industry: 'Enterprise',
    description: 'Analytical engine for SQL querying, data visualization, and predictive modeling.',
    features: ['SQL Querying', 'Data Visualization', 'Report Generation', 'Trend Analysis', 'Predictive Modeling'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 5000,
    price: '₹50,000/month',
    icon: Database,
    color: 'indigo',
    roi: 'Accelerates data reporting to real-time',
    complexity: 'Expert',
  },
  {
    id: '13',
    name: 'Software Developer Agent',
    type: 'engineering',
    industry: 'Technology',
    description: 'Coding assistant for PR reviews, bug detection, and code scaffolding.',
    features: ['PR Reviews', 'Bug Detection', 'Documentation Generation', 'Code Scaffolding', 'Refactoring'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹60,000/month',
    icon: Code,
    color: 'sky',
    roi: 'Increases developer throughput by 40%',
    complexity: 'Expert',
  },
  {
    id: '14',
    name: 'Customer Success Agent',
    type: 'customer_success',
    industry: 'B2B',
    description: 'Post-sales success agent for onboarding customers, tracking renewals, and reducing churn.',
    features: ['Onboarding Playbooks', 'Health Score Summaries', 'Renewal Reminders', 'QBR Prep', 'Escalation Triage'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹28,000/month',
    icon: HeartHandshake,
    color: 'emerald',
    roi: 'Improves retention by 10–20%',
    complexity: 'Basic',
  },
  {
    id: '15',
    name: 'Recruiting Agent',
    type: 'recruiting',
    industry: 'Enterprise',
    description: 'Recruiting assistant for sourcing, screening, interview scheduling, and candidate communications.',
    features: ['Resume Screening', 'Candidate Outreach', 'Interview Scheduling', 'Scorecards', 'ATS Notes Drafting'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹32,000/month',
    icon: UserSearch,
    color: 'purple',
    roi: 'Cuts time-to-screen by 50%',
    complexity: 'Advanced',
  },
  {
    id: '16',
    name: 'Payroll & Benefits Agent',
    type: 'payroll',
    industry: 'Enterprise',
    description: 'Payroll/benefits helpdesk agent for payslip questions, tax forms, and benefits enrollment support.',
    features: ['Payslip Explainers', 'Form Guidance', 'Benefits FAQ', 'Enrollment Nudges', 'Policy Routing'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3500,
    price: '₹40,000/month',
    icon: BadgeDollarSign,
    color: 'amber',
    roi: 'Reduces HR tickets by 30%',
    complexity: 'Basic',
  },
  {
    id: '17',
    name: 'Security Operations Agent',
    type: 'security_ops',
    industry: 'Technology',
    description: 'SOC assistant for triage, alert enrichment, playbook execution, and escalation summaries.',
    features: ['Alert Enrichment', 'Triage Summaries', 'Playbook Checklists', 'Incident Handoff Notes', 'Evidence Collection'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 6500,
    price: '₹70,000/month',
    icon: Shield,
    color: 'rose',
    roi: 'Speeds triage by 2–3x',
    complexity: 'Expert',
  },
  {
    id: '18',
    name: 'DevOps Agent',
    type: 'devops',
    industry: 'Technology',
    description: 'DevOps assistant for incident comms, runbook guidance, CI/CD troubleshooting, and service health checks.',
    features: ['Runbook Guidance', 'Deploy Checklists', 'Log Summaries', 'SLO/SLI Notes', 'Postmortem Drafting'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 4000,
    price: '₹45,000/month',
    icon: Server,
    color: 'cyan',
    roi: 'Reduces MTTR by 20%',
    complexity: 'Advanced',
  },
  {
    id: '19',
    name: 'QA Testing Agent',
    type: 'qa',
    industry: 'Technology',
    description: 'QA assistant for test case generation, bug reproduction steps, and release quality checklists.',
    features: ['Test Case Drafting', 'Bug Triage', 'Repro Steps', 'Release Checklists', 'Acceptance Criteria Review'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹27,000/month',
    icon: Bug,
    color: 'indigo',
    roi: 'Improves regression coverage by 30%',
    complexity: 'Basic',
  },
  {
    id: '20',
    name: 'Procurement Agent',
    type: 'procurement',
    industry: 'Enterprise',
    description: 'Procurement assistant for vendor comparisons, RFQ drafting, approvals, and contract intake.',
    features: ['RFQ Drafting', 'Vendor Comparison', 'Approval Routing', 'Policy Checks', 'Savings Tracking'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹33,000/month',
    icon: ClipboardList,
    color: 'teal',
    roi: 'Improves purchasing cycle time by 25%',
    complexity: 'Advanced',
  },
  {
    id: '21',
    name: 'Logistics Agent',
    type: 'logistics',
    industry: 'E-commerce',
    description: 'Logistics assistant for shipment tracking, carrier updates, delivery exceptions, and customer updates.',
    features: ['Shipment Tracking', 'Delivery Exception Handling', 'Carrier Updates', 'Customer Notifications', 'Return Routing'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2200,
    price: '₹26,000/month',
    icon: Truck,
    color: 'orange',
    roi: 'Reduces "Where is my order?" tickets',
    complexity: 'Basic',
  },
  {
    id: '22',
    name: 'Documentation Agent',
    type: 'documentation',
    industry: 'Technology',
    description: 'Documentation assistant for writing, updating, and validating product docs and internal runbooks.',
    features: ['Docs Drafting', 'Change Summaries', 'Runbook Updates', 'Style Consistency', 'FAQ Generation'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 2500,
    price: '₹30,000/month',
    icon: FileText,
    color: 'sky',
    roi: 'Cuts docs effort by 40%',
    complexity: 'Basic',
  },
  {
    id: '23',
    name: 'Call Center Agent',
    type: 'call_center',
    industry: 'E-commerce',
    description: 'Voice/chat-ready agent for call summaries, next-best actions, and consistent customer responses.',
    features: ['Call Summaries', 'Suggested Replies', 'Disposition Tags', 'Knowledge Base Lookup', 'Escalation Handoff'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹34,000/month',
    icon: PhoneCall,
    color: 'blue',
    roi: 'Improves handle time by 15%',
    complexity: 'Advanced',
  },
  {
    id: '24',
    name: 'Facilities Agent',
    type: 'facilities',
    industry: 'Enterprise',
    description: 'Facilities assistant for service requests, vendor dispatch, maintenance schedules, and workplace FAQs.',
    features: ['Service Requests', 'Vendor Dispatch', 'Maintenance Schedules', 'Access Coordination', 'Workplace FAQ'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹21,000/month',
    icon: Building2,
    color: 'slate',
    roi: 'Improves request resolution speed',
    complexity: 'Basic',
  },
  {
    id: '25',
    name: 'Learning & Development Agent',
    type: 'learning',
    industry: 'Enterprise',
    description: 'L&D assistant for course recommendations, learning paths, quiz generation, and training reminders.',
    features: ['Learning Paths', 'Course Recommendations', 'Quizzes', 'Training Reminders', 'Progress Summaries'],
    model: 'google/gemini-2.0-flash-001',
    platform: 'Google',
    budget: 2000,
    price: '₹24,000/month',
    icon: GraduationCap,
    color: 'purple',
    roi: 'Increases completion rates',
    complexity: 'Basic',
  },
  {
    id: 'custom',
    name: 'Create Custom Agent',
    type: 'custom',
    industry: 'All',
    description: 'Build your own specialized AI agent from scratch with custom instructions, tools, and selected models.',
    features: ['Custom System Prompt', 'Any Supported Model', 'Custom Tool Integrations', 'Domain Specific Knowledge', 'Custom Sandbox'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 0,
    price: 'Pay as you go',
    icon: Plus,
    color: 'slate',
    roi: 'Tailored perfectly for your use case',
    complexity: 'Advanced',
  },
];
